%%
%% test_xdr was generated by erpcgen (do not edit)
%%
-module(test_xdr).
-export([enc_t_enum/1, dec_t_enum/2, dec_t_enum_i2a/1]).
-export([enc_t_primitive_struct/1, dec_t_primitive_struct/2]).
-export([enc_t_union_e/1, dec_t_union_e/2]).
-export([enc_t_union_i/1, dec_t_union_i/2]).
-export([enc_t_optional/1, dec_t_optional/2]).
-export([enc_t_struct/1, dec_t_struct/2]).

enc_t_enum(_1) ->
    case _1 of
        'T_ENUM_0' ->
            <<0:32>>;
        'T_ENUM_1' ->
            <<1:32>>;
        'T_ENUM_2' ->
            <<2:32>>
    end.

dec_t_enum(_1, _2) ->
    begin
        <<_:_2/binary,_3:32,_/binary>> = _1,
        case _3 of
            0 ->
                {'T_ENUM_0', _2 + 4};
            1 ->
                {'T_ENUM_1', _2 + 4};
            2 ->
                {'T_ENUM_2', _2 + 4}
        end
    end.

dec_t_enum_i2a(_4) ->
    case _4 of
        0 ->
            'T_ENUM_0';
        1 ->
            'T_ENUM_1';
        2 ->
            'T_ENUM_2'
    end.

enc_t_primitive_struct(_1) ->
    case _1 of
        {_14, _13, _12, _11, _10, _9, _8, _6, _4, _2} ->
            [<<_14:32>>,
             <<_13:32>>,
             enc_t_enum(_12),
             if
                 _11 == true ->
                     <<1:32>>;
                 _11 == false ->
                     <<0:32>>
             end,
             <<_10:64>>,
             <<_9:64>>,
             case io_list_len(_8) of
                 3 ->
                     [_8, <<0:8>>];
                 _ ->
                     exit({xdr, limit})
             end,
             begin
                 _7 = io_list_len(_6),
                 if
                     _7 =< 5 ->
                         [<<_7:32/unsigned>>, _6, enc_align(_7)];
                     true ->
                         exit({xdr, limit})
                 end
             end,
             begin
                 _5 = io_list_len(_4),
                 [<<_5:32/unsigned>>, _4, enc_align(_5)]
             end,
             begin
                 _3 = io_list_len(_2),
                 if
                     _3 =< 5 ->
                         [<<_3:32/unsigned>>, _2, enc_align(_3)];
                     true ->
                         exit({xdr, limit})
                 end
             end]
    end.

dec_t_primitive_struct(_1, _2) ->
    begin
        begin
            <<_:_2/binary,_3:32/signed,_/binary>> = _1,
            _4 = _2 + 4
        end,
        begin
            <<_:_4/binary,_5:32/unsigned,_/binary>> = _1,
            _6 = _4 + 4
        end,
        {_7, _8} = dec_t_enum(_1, _6),
        begin
            begin
                <<_:_8/binary,_11:32/unsigned,_/binary>> = _1,
                _9 =
                    if
                        _11 == 0 ->
                            false;
                        _11 == 1 ->
                            true
                    end
            end,
            _10 = _8 + 4
        end,
        begin
            <<_:_10/binary,_12:64/signed,_/binary>> = _1,
            _13 = _10 + 8
        end,
        begin
            <<_:_13/binary,_14:64/unsigned,_/binary>> = _1,
            _15 = _13 + 8
        end,
        begin
            <<_:_15/binary,_16:3/binary,_/binary>> = _1,
            _17 = _15 + 4
        end,
        {_18, _19} =
            begin
                <<_:_17/binary,_20:32/unsigned,_/binary>> = _1,
                if
                    _20 > 5 ->
                        exit({xdr, limit});
                    true ->
                        _21 = _17 + 4,
                        <<_:_21/binary,_22:_20/binary,_/binary>> = _1,
                        {_22, _21 + align(_20)}
                end
            end,
        {_23, _24} =
            begin
                <<_:_19/binary,_25:32/unsigned,_/binary>> = _1,
                _26 = _19 + 4,
                <<_:_26/binary,_27:_25/binary,_/binary>> = _1,
                {_27, _26 + align(_25)}
            end,
        {_28, _29} =
            begin
                <<_:_24/binary,_30:32/unsigned,_/binary>> = _1,
                if
                    _30 > 5 ->
                        exit({xdr, limit});
                    true ->
                        _31 = _24 + 4,
                        <<_:_31/binary,_32:_30/binary,_/binary>> = _1,
                        {_32, _31 + align(_30)}
                end
            end,
        {{_3, _5, _7, _9, _12, _14, _16, _18, _23, _28}, _29}
    end.

enc_t_union_e(_1) ->
    case _1 of
        {_2, _3} ->
            [enc_t_enum(_2),
             case _2 of
                 'T_ENUM_0' ->
                     <<_3:32>>;
                 'T_ENUM_1' ->
                     enc_t_primitive_struct(_3)
             end]
    end.

dec_t_union_e(_1, _2) ->
    begin
        <<_:_2/binary,_3:32/signed,_/binary>> = _1,
        _6 = _2 + 4,
        case _3 of
            0 ->
                begin
                    <<_:_6/binary,_4:32/signed,_/binary>> = _1,
                    _5 = _6 + 4
                end,
                {{'T_ENUM_0', _4}, _5};
            1 ->
                {_4, _5} = dec_t_primitive_struct(_1, _6),
                {{'T_ENUM_1', _4}, _5}
        end
    end.

enc_t_union_i(_1) ->
    case _1 of
        {_2, _3} ->
            [<<_2:32>>,
             case _2 of
                 3 ->
                     <<_3:32>>;
                 6 ->
                     enc_t_primitive_struct(_3)
             end]
    end.

dec_t_union_i(_1, _2) ->
    begin
        <<_:_2/binary,_3:32/signed,_/binary>> = _1,
        _6 = _2 + 4,
        case _3 of
            3 ->
                begin
                    <<_:_6/binary,_4:32/signed,_/binary>> = _1,
                    _5 = _6 + 4
                end,
                {{3, _4}, _5};
            6 ->
                {_4, _5} = dec_t_primitive_struct(_1, _6),
                {{6, _4}, _5}
        end
    end.

enc_t_optional(_1) ->
    case _1 of
        void ->
            <<0:32>>;
        _ ->
            [<<1:32>>,
             case _1 of
                 {_3, _2} ->
                     [<<_3:32>>, enc_t_optional(_2)]
             end]
    end.

dec_t_optional(_1, _2) ->
    begin
        <<_:_2/binary,_3:32/unsigned,_/binary>> = _1,
        _4 = _2 + 4,
        if
            _3 == 0 ->
                {void, _4};
            _3 == 1 ->
                begin
                    begin
                        <<_:_4/binary,_5:32/signed,_/binary>> = _1,
                        _6 = _4 + 4
                    end,
                    {_7, _8} = dec_t_optional(_1, _6),
                    {{_5, _7}, _8}
                end
        end
    end.

enc_t_struct(_1) ->
    case _1 of
        {_6, _5, _2} ->
            [if
                 length(_6) == 2 ->
                     lists:map(fun(_7) ->
                                      enc_t_primitive_struct(_7)
                               end,
                               _6)
             end,
             enc_t_union_e(_5),
             begin
                 _4 = length(_2),
                 if
                     _4 =< 5 ->
                         [<<_4:32/unsigned>>,
                          lists:map(fun(_3) ->
                                           enc_t_primitive_struct(_3)
                                    end,
                                    _2)];
                     true ->
                         exit({xdr, limit})
                 end
             end]
    end.

dec_t_struct(_1, _2) ->
    begin
        {_3, _4} =
            map_elem(fun(_5, _6) ->
                            dec_t_primitive_struct(_5, _6)
                     end,
                     _1, _2, infinity, 2),
        {_7, _8} = dec_t_union_e(_1, _4),
        {_9, _10} =
            begin
                <<_:_8/binary,_11:32/unsigned,_/binary>> = _1,
                map_elem(fun(_12, _13) ->
                                dec_t_primitive_struct(_12, _13)
                         end,
                         _1,
                         _8 + 4,
                         5, _11)
            end,
        {{_3, _7, _9}, _10}
    end.

map_elem(Fun, Bin, Off, infinity, N) ->
  map_elem0(Fun, Bin, Off, N, []);
map_elem(Fun, Bin, Off, Max, N) when N =< Max ->
  map_elem0(Fun, Bin, Off, N, []).

map_elem0(_Fun, _Bin, Off, 0, L) ->
  {lists:reverse(L,[]), Off};
map_elem0(Fun, Bin, Off, N, L) ->
  {E,Off1} = Fun(Bin, Off),
map_elem0(Fun, Bin, Off1, N-1, [E|L]).

io_list_len(L) -> io_list_len(L, 0).
io_list_len([H|T], N) ->
  if
    H >= 0, H =< 255 -> io_list_len(T, N+1);
    is_list(H) -> io_list_len(T, io_list_len(H,N));
    is_binary(H) -> io_list_len(T, size(H) + N);
    true -> exit({xdr, opaque})
  end;
io_list_len(H, N) when is_binary(H) ->
  size(H) + N;
io_list_len([], N) ->
N.

enc_align(Len) ->
  case Len rem 4 of
    0 -> <<>>;
    1 -> <<0,0,0>>;
    2 -> <<0,0>>;
    3 -> <<0>>
  end.

align(Len) ->
  case Len rem 4 of
    0 -> Len;
    1 -> Len+3;
    2 -> Len+2;
    3 -> Len+1
  end.
